[package]
name = "bevy_label"
version = "0.9.0"
edition = "2021"
description = "Traits used by label implementations."
homepage = "https://bevyengine.org"
repository = "https://github.com/bevyengine/bevy"
license = "MIT OR Apache-2.0"
keywords = ["bevy", "no_std"]
